// flow-typed signature: 33a55146114aa5041bd05cca9e3a75f6
// flow-typed version: <<STUB>>/pixel-diff_v^1.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixel-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixel-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixel-diff/Gruntfile' {
  declare module.exports: any;
}

declare module 'pixel-diff/test/unit.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixel-diff/Gruntfile.js' {
  declare module.exports: $Exports<'pixel-diff/Gruntfile'>;
}
declare module 'pixel-diff/index' {
  declare module.exports: $Exports<'pixel-diff'>;
}
declare module 'pixel-diff/index.js' {
  declare module.exports: $Exports<'pixel-diff'>;
}
declare module 'pixel-diff/test/unit.spec.js' {
  declare module.exports: $Exports<'pixel-diff/test/unit.spec'>;
}
