// flow-typed signature: 47de06779fc0dfd7a80a054a5075ea70
// flow-typed version: <<STUB>>/rc_v1.2.7/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc/browser' {
  declare module.exports: any;
}

declare module 'rc/cli' {
  declare module.exports: any;
}

declare module 'rc/lib/utils' {
  declare module.exports: any;
}

declare module 'rc/test/ini' {
  declare module.exports: any;
}

declare module 'rc/test/nested-env-vars' {
  declare module.exports: any;
}

declare module 'rc/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc/browser.js' {
  declare module.exports: $Exports<'rc/browser'>;
}
declare module 'rc/cli.js' {
  declare module.exports: $Exports<'rc/cli'>;
}
declare module 'rc/index' {
  declare module.exports: $Exports<'rc'>;
}
declare module 'rc/index.js' {
  declare module.exports: $Exports<'rc'>;
}
declare module 'rc/lib/utils.js' {
  declare module.exports: $Exports<'rc/lib/utils'>;
}
declare module 'rc/test/ini.js' {
  declare module.exports: $Exports<'rc/test/ini'>;
}
declare module 'rc/test/nested-env-vars.js' {
  declare module.exports: $Exports<'rc/test/nested-env-vars'>;
}
declare module 'rc/test/test.js' {
  declare module.exports: $Exports<'rc/test/test'>;
}
